name: Beta check

on:
  push:
    branches: [ beta-ci ]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: "24.x"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-26, ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          version: 11
          run_install: false

      - name: Setup NodeJS
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Launch tests
        uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        with:
          run: pnpm test

      - name: Package (macOS)
        if: startsWith(matrix.os, 'macos')
        run: pnpm electron-builder --mac dmg:arm64 dmg:x64 -p never

      - name: Package (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: pnpm electron-builder --linux AppImage:x64 deb:x64 -p never

      - name: Package (Windows)
        if: startsWith(matrix.os, 'windows')
        run: pnpm electron-builder --win nsis:x64 zip:x64 -p never

      - name: Upload
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: beta-${{ matrix.os }}
          if-no-files-found: error
          path: |
            pack/*.dmg
            pack/*.AppImage
            pack/*.deb
            pack/*.exe
            pack/*.zip
